<script>
  import ArticleHeader from '$lib/components/Article/ArticleHeader.svelte';
  import Map from '$lib/components/Maps/Map.svelte';
  import MapLayer from '$lib/components/Maps/MapLayer.svelte';
  import Geocoder from '$lib/components/Maps/Geocoder.svelte';
  import Legend from '$lib/components/Maps/Legend.svelte';

  let { data } = $props();

  const packagesGeoJson = $derived.by(() => ({
    type: 'FeatureCollection',
    features: (data.packages ?? [])
      .map((p) => {
        const lng = Number(p.longitude);
        const lat = Number(p.latitude);

        if (!Number.isFinite(lng) || !Number.isFinite(lat)) return null;

        return {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [lng, lat],
          },
          properties: {
            boro_nm: p.boro_nm,
            typ_desc: p.typ_desc,
            package_type: String(p.typ_desc || '')
              .split(':')[1]
              ?.trim()
              .toLowerCase(),
            create_date: p.create_date,
          },
        };
      })
      .filter(Boolean),
  }));

  let longitude = $state(-74.0);
  let latitude = $state(40.7);
  let zoom = $state(9.5);

  function formatDate(value) {
    if (!value) return '';

    const datePart = String(value).split('T')[0];
    const [year, month, day] = datePart.split('-');

    if (!year || !month || !day) return datePart;

    return `${day}/${month}/${year}`;
  }
</script>

<div class="container">
    <ArticleHeader
    headline="Have you seen this suspicious package?"
    byline="Ashley Mowreader"
    pubDate="2026-04-26"
  />

  <p>
   Each year, the New York Police Department responds to thousands of reports of suspicious packages. Some are harmless, but others can pose serious threats. 
   </p>
   <p>This interactive map shows the locations of reported suspicious packages in New York City in 2024 (the latest update to data), based on reports from the NYPD's Open Data portal. </p>
  
  <p> Click on a datapoint to learn more about the report or use the search box to find your neighborhood and see if there have been any reports nearby.
  </p>

    <Geocoder
    label="Explore your neighborhood"
    placeholder="Enter an address in New York…"
    onresult={(result) => {
      longitude = result.lng;
      latitude = result.lat;
      zoom = 15;
    }}
  />

       <Legend
        title="Locations of Suspicious Packages"
        mode="categorical"
        items={[
          { color: '#16a34a', label: 'Outside' },
          { color: '#1d4ed8', label: 'Inside' },
          { color: '#f97316', label: 'Transit' },
        ]}
      />

  <Map
    {longitude}
    {latitude}
    {zoom}
    height ={600}
    theme="positron"
    credit="OpenFreeMap / OpenStreetMap contributors"
  >
    <MapLayer
      id="packages"
      type="circle"
      data={packagesGeoJson}
      paint={{
        'circle-color': [
          'match',
          ['get', 'package_type'],
          'transit', '#f97316',
          'outside', '#16a34a',
          'inside', '#1d4ed8',
          '#6b7280',
        ],
        'circle-radius': 5,
        'circle-stroke-color': '#1a1a1a',
        'circle-stroke-width': 1,
        'circle-opacity': 0.9,
      }}

      popup={(feature) => {
        const p = feature.properties;
        return `<strong>${p.typ_desc || 'Suspicious package'}</strong><br>${p.boro_nm || ''}<br>${formatDate(p.create_date)}`;
      }}
    />
   
  </Map>


  <div class ="methodology">
    <h2>Methodology</h2>
    <p>
      The data for this map was sourced from the New York Police Department's Open Data portal, specifically from the "NYPD Calls for Service (Historic)" dataset. Entries are generated by members of the public who called 911, as well as by police officers in the field.</p>
      <p>
      The dataset has been filtered to include only incidents reported in 2024 that were categorized as "SUSP PACKAGE". Packages are categorized by their location, as labeled in the portal. Other relevant fields extracted for this visualization include the incident date, location description, and geographic coordinates (latitude and longitude). The data was then processed and formatted for use in this interactive map.
    </p>

    </div>
</div>